# Generated by Django 5.2.3 on 2025-06-13 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subrubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subrubros', to='core.rubro')),
            ],
            options={
                'verbose_name': 'Subrubro',
                'verbose_name_plural': 'Subrubros',
                'ordering': ['rubro__nombre', 'nombre'],
                'unique_together': {('nombre', 'rubro')},
            },
        ),
    ]
