# Generated by Django 5.2.3 on 2025-06-13 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Rubro',
                'verbose_name_plural': 'Rubros',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Subrubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subrubros', to='general.rubro')),
            ],
            options={
                'verbose_name': 'Subrubro',
                'verbose_name_plural': 'Subrubros',
                'ordering': ['rubro__nombre', 'nombre'],
                'unique_together': {('nombre', 'rubro')},
            },
        ),
    ]
