# Generated by Django 5.2.2 on 2026-02-12 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_add_obra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='companymembership',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Admin de la empresa: puede gestionar usuarios y tiene acceso a todas las secciones.'),
        ),
        migrations.CreateModel(
            name='CompanyMembershipSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_sections', to='general.companymembership')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_sections', to='general.section')),
            ],
            options={
                'unique_together': {('membership', 'section')},
            },
        ),
        migrations.AddField(
            model_name='companymembership',
            name='sections',
            field=models.ManyToManyField(blank=True, help_text='Secciones a las que tiene acceso. Admins ignoran esto.', related_name='memberships', through='general.CompanyMembershipSection', to='general.section'),
        ),
    ]
