# Generated by Django 5.2.3 on 2025-06-13 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad_por_unidad_venta', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ('precio_unidad_venta', models.DecimalField(decimal_places=4, max_digits=12)),
                ('moneda', models.CharField(choices=[('ARS', 'Pesos Argentinos (ARS)'), ('USD', 'Dólares Estadounidenses (USD)')], default='ARS', max_length=3)),
                ('subrubro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales', to='general.subrubro')),
                ('unidad_de_venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiales_vendidos', to='general.unidad')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Subcontrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, unique=True)),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('precio_por_unidad', models.DecimalField(decimal_places=4, max_digits=12)),
                ('moneda', models.CharField(choices=[('ARS', 'Pesos Argentinos (ARS)'), ('USD', 'Dólares Estadounidenses (USD)')], default='ARS', max_length=3)),
                ('unidad_de_analisis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subcontratos_unidades', to='general.unidad')),
            ],
            options={
                'verbose_name': 'Subcontrato',
                'verbose_name_plural': 'Subcontratos',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='ManoDeObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_puesto', models.CharField(max_length=200)),
                ('equipo', models.CharField(choices=[('Naty', 'Equipo Naty'), ('Diego', 'Equipo Diego')], max_length=50)),
                ('precio_por_unidad', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unidad_de_analisis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mano_de_obra_unidades', to='general.unidad')),
            ],
            options={
                'verbose_name': 'Mano de Obra',
                'verbose_name_plural': 'Mano de Obra',
                'ordering': ['descripcion_puesto'],
                'unique_together': {('descripcion_puesto', 'equipo')},
            },
        ),
    ]
