# Generated by Django 5.2.3 on 2025-06-13 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_proveedor'),
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales', to='general.proveedor'),
        ),
    ]
