# Generated by Django 5.2.2 on 2026-02-12 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HojaPrecios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('origen', models.ForeignKey(blank=True, help_text='Hoja desde la que se creó esta copia, si aplica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copias', to='recursos.hojaprecios')),
            ],
            options={
                'verbose_name': 'Hoja de Precios',
                'verbose_name_plural': 'Hojas de Precios',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='HojaPrecioMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_por_unidad_venta', models.DecimalField(decimal_places=4, max_digits=10)),
                ('precio_unidad_venta', models.DecimalField(decimal_places=4, max_digits=12)),
                ('moneda', models.CharField(choices=[('ARS', 'Pesos Argentinos (ARS)'), ('USD', 'Dólares Estadounidenses (USD)')], default='ARS', max_length=3)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hojas_precios', to='recursos.material')),
                ('hoja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='recursos.hojaprecios')),
            ],
            options={
                'verbose_name': 'Precio de Material en Hoja',
                'verbose_name_plural': 'Precios de Material en Hoja',
                'ordering': ['material__nombre'],
            },
        ),
    ]
