# Generated by Django 5.2.3 on 2026-02-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0012_add_dolar'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tarearecurso',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('material__isnull', False), ('mano_de_obra__isnull', True), ('subcontrato__isnull', True), ('mezcla__isnull', True)), models.Q(('material__isnull', True), ('mano_de_obra__isnull', False), ('subcontrato__isnull', True), ('mezcla__isnull', True)), models.Q(('material__isnull', True), ('mano_de_obra__isnull', True), ('subcontrato__isnull', False), ('mezcla__isnull', True)), models.Q(('material__isnull', True), ('mano_de_obra__isnull', True), ('subcontrato__isnull', True), ('mezcla__isnull', False)), _connector='OR'), name='tarea_recurso_exactly_one_resource'),
        ),
        migrations.AddConstraint(
            model_name='tarearecurso',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='tarea_recurso_cantidad_gt_zero'),
        ),
    ]
